build: convert build scripts to Kotlin and target Java 17
PaperMC/bibliothek pull request #73
Opened 2021-11-29 04:23 UTC by broccolai

closes #71 and #72

2021-11-29 07:10 UTC, Proximyst commented on build.gradle.kts
> +  val indraVersion = "2.0.6"
Might as well just use the aliases with version catalogs?

2021-11-29 19:41 UTC, broccolai commented
Updated the Dockerfile too but I am by no means a docker expert so that should definitely be reviewed :')

2021-11-29 20:07 UTC, yannicklamprecht requested changes

2021-11-29 20:07 UTC, yannicklamprecht commented on Dockerfile
> +FROM openjdk:${JAVA_VERSION}-slim AS builder
You likely want the JDK for compiling the project.

`openjdk:17-jdk-slim`


```suggestion
FROM openjdk:${JAVA_VERSION}-jdk-slim AS builder
```

2021-11-29 23:17 UTC, yannicklamprecht approved these changes
LGTM

Probably a follow up task would be to check if a general dependency can be upgrade.
Just as a recurring task or by using dependabot.

2021-11-30 02:27 UTC, kashike approved these changes

2021-11-30 03:27 UTC, merged